### ISSUE TITLE
error with "vertices"

### ISSUE THREAD

**Issue by dangcap07** [RedHenDev/ursina_tutorials#10]
so i am on video tutorial 11 and i am getting an error: 'panda3d.core.NodePath' object has no attribute 'vertices'. how can i fix it? Is there something similar to vertives as an alternative?

**Comment by RedHenDev** [comment]
I'll have a look at that video -- I'll write again asap...

**Comment by RedHenDev** [comment]
Oh -- have you tried using my tut 11 code on your machine? Does my code give you the same issue?

**Comment by RedHenDev** [comment]
Thanks for your comment on the video. A problem with the version of ursina.

**Comment by luis605** [comment]
What ursina version should I use?

**Comment by davem1988** [comment]
I Have the same problem i tried with your code and same error happens. How can i fix it? it seems to be relatetd to the ursina version.
