### ISSUE TITLE
Mechanism to control gravity (switching between lerping and pressing space to jump)

### ISSUE THREAD

**Issue by HeyItsAnushtubh** [RedHenDev/ursina_tutorials#2]
# Download this file of code (scroll down to see why it is a text file)
[ControlledGravity_pyCraft.txt](https://github.com/RedHenDev/ursina_tutorials/files/6950646/ControlledGravity_pyCraft.txt)

# ChangeLog:
 Added new function to control gravity (gravityTool) (activated/deactivited on pressing 'e')
 New variable to support the function (gravityMode)
 New name for New Gravity system Function (NewGravity)
 Added it bcs you couldn't jump on new created blocks that are not a part of the terrain

Sorry, couldn't make it into a code block, bcs of some glitch in github, pls take the code from the txt and paste it into a .py file (github doesn't support uploading .py files idk why...)

Did things mentioned in the changelog
Thanks! :smiley:

**Comment by ethan575** [comment]
you could copy your code and wrap it in ` it would look like this `print("Hello world")
for multiple lines of code wrap it in ```
