### ISSUE TITLE
meshcraft - perf improvement, simpler code with tuple for terrain dict instead of str format entries

### ISSUE THREAD

**Issue by lessw2020** [RedHenDev/ursina_tutorials#9]
I just wanted to note that you can both speed up and simplify the structure for the terrain dict by storing the xyz coords as a number tuple rather than the "x"+str(x)" etc. format currently used.
A tuple can be hashed to form the lookup for the dict and thus no need to push it into a string format first.  

Thus:
~~~ 
td.get((x,y,z))  
~~~
![tuple_dict](https://user-images.githubusercontent.com/46302957/148699650-f0398a0b-4d4f-41dc-a674-119a34d07dc4.png)

**Comment by lessw2020** [comment]
and of course, just wanted to note that this tutorial series is fantastic! :)

**Comment by RedHenDev** [comment]
This is stunning!

Thank you so much -- and really appreciate the crystal clear example of improved code. Wonderful, thank you.
